#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
#           This file was automatically generated from src/transformers/models/qwen2/modular_qwen2.py.
#               Do NOT edit this file manually as any edits will be overwritten by the generation of
#             the file from the modular. If any change should be done, please apply the change to the
#                          modular_qwen2.py file directly. One of our CI enforces this.
#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
from typing import List, Optional, Union

import torch
from torch import nn
from transformers import CLIPConfig, CLIPVisionModel, CLIPVisionConfig, Qwen2Model, Qwen2ForCausalLM, Qwen2Config
from transformers.cache_utils import Cache, DynamicCache
from transformers.masking_utils import create_causal_mask, create_sliding_window_causal_mask
from transformers.modeling_outputs import BaseModelOutputWithPast, CausalLMOutputWithPast
from transformers.processing_utils import Unpack
from transformers.utils import TransformersKwargs, auto_docstring, can_return_tuple

def merge_configs(base_config, override_config):
    """Merge two Hugging Face config objects"""
    # Handle None cases
    if override_config is None:
        return base_config
    if base_config is None:
        return override_config
    
    # Convert configs to dictionaries
    base_dict = base_config.to_dict()
    override_dict = override_config.to_dict()
    
    # Deep merge
    def deep_merge(base, override):
        for key, value in override.items():
            if key in base and isinstance(base[key], dict) and isinstance(value, dict):
                deep_merge(base[key], value)
            else:
                base[key] = value
    
    deep_merge(base_dict, override_dict)
    
    # Create new config from merged dictionary
    return type(base_config)(**base_dict)

class CrossAttentionAdapter(nn.Module):
    def __init__(self, hidden_size, vision_hidden_size, num_heads=8):
        super().__init__()
        self.cross_attn = nn.MultiheadAttention(
            embed_dim=hidden_size,
            num_heads=num_heads,
            kdim=vision_hidden_size,
            vdim=vision_hidden_size,
            batch_first=True
        )
        self.norm = nn.LayerNorm(hidden_size)
        self.gate = nn.Parameter(torch.zeros(1))
        
    def forward(self, text_hidden, vision_features):
        attn_out, _ = self.cross_attn(
            query=text_hidden,
            key=vision_features,
            value=vision_features
        )
        return text_hidden + self.gate * self.norm(attn_out)

class RTVTLMConfig(Qwen2Config):
    def __init__(self, adapter_insert_positions: List[int] = None, vision_config : CLIPVisionConfig = None, **kwargs):
        super().__init__(**kwargs)
        self.vision_config = vision_config
        self.adapter_insert_positions = adapter_insert_positions

@auto_docstring
class RTVTLMModel(Qwen2Model):
    def __init__(self, config: RTVTLMConfig):
        super().__init__(config)

        # Load vision encoder with compatible settings
        insert_positions = config.adapter_insert_positions 
        self.adapters = nn.ModuleDict({
            str(layer_idx): CrossAttentionAdapter(config.hidden_size, config.vision_config.hidden_size, num_heads=8)
            for layer_idx in insert_positions
        })
        
        # Cache for vision features during generation
        self._vision_features_cache = None
        self.post_init()

    @classmethod
    def from_pretrained(cls, 
                        config: RTVTLMConfig):
        """Load pretrained language and vision models"""
        model = super().from_pretrained.__func__(cls, config)
        return model.to(device=model.device, dtype=model.dtype)

    @auto_docstring
    def forward(
        self,
        vision_features: Optional[torch.FloatTensor] = None,
        input_ids: Optional[torch.LongTensor] = None,
        attention_mask: Optional[torch.Tensor] = None,
        position_ids: Optional[torch.LongTensor] = None,
        past_key_values: Optional[Cache] = None,
        inputs_embeds: Optional[torch.FloatTensor] = None,
        use_cache: Optional[bool] = None,
        cache_position: Optional[torch.LongTensor] = None,
        **kwargs: Unpack[TransformersKwargs],
    ) -> BaseModelOutputWithPast:
        """
        Args:
            vision_features (`torch.FloatTensor` of shape `(batch_size, sequence_length, hidden_size)`, *optional*):
                Vision features from the vision encoder to be integrated via cross-attention adapters.
        """
        if (input_ids is None) ^ (inputs_embeds is not None):
            raise ValueError("You must specify exactly one of input_ids or inputs_embeds")
    
        if inputs_embeds is None:
            inputs_embeds = self.embed_tokens(input_ids)

        if use_cache and past_key_values is None:
            past_key_values = DynamicCache(config=self.config)

        if cache_position is None:
            past_seen_tokens = past_key_values.get_seq_length() if past_key_values is not None else 0
            cache_position = torch.arange(
                past_seen_tokens, past_seen_tokens + inputs_embeds.shape[1], device=inputs_embeds.device
            )

        if position_ids is None:
            position_ids = cache_position.unsqueeze(0)

        # It may already have been prepared by e.g. `generate`
        if not isinstance(causal_mask_mapping := attention_mask, dict):
            # Prepare mask arguments
            mask_kwargs = {
                "config": self.config,
                "input_embeds": inputs_embeds,
                "attention_mask": attention_mask,
                "cache_position": cache_position,
                "past_key_values": past_key_values,
                "position_ids": position_ids,
            }
            # Create the masks
            causal_mask_mapping = {
                "full_attention": create_causal_mask(**mask_kwargs),
            }
            # The sliding window alternating layers are not always activated depending on the config
            if self.has_sliding_layers:
                causal_mask_mapping["sliding_attention"] = create_sliding_window_causal_mask(**mask_kwargs)

        hidden_states = inputs_embeds

        # create position embeddings to be shared across the decoder layers
        position_embeddings = self.rotary_emb(hidden_states, position_ids)

        for i, decoder_layer in enumerate(self.layers[: self.config.num_hidden_layers]):
            hidden_states = decoder_layer(
                hidden_states,
                attention_mask=causal_mask_mapping[decoder_layer.attention_type],
                position_ids=position_ids,
                past_key_values=past_key_values,
                use_cache=use_cache,
                cache_position=cache_position,
                position_embeddings=position_embeddings,
                **kwargs,
            )
            if str(i) in list(self.adapters.keys()):
                hidden_states = self.adapters[str(i)](hidden_states, vision_features)

        hidden_states = self.norm(hidden_states)
        return BaseModelOutputWithPast(
            last_hidden_state=hidden_states,
            past_key_values=past_key_values if use_cache else None,
        )

@auto_docstring
class RTVTLMForCausalLM(Qwen2ForCausalLM):
    def __init__(self, config: RTVTLMConfig):
        super().__init__(config)
        self.model = RTVTLMModel(config=config)
        self.vision_embedder = CLIPVisionModel(config=config.vision_config)
        self.vocab_size = config.vocab_size
        self.lm_head = nn.Linear(config.hidden_size, self.vocab_size, bias=False)
    
        # Initialize weights and apply final processing
        self.post_init()

    @classmethod
    def from_pretrained(cls, language_model_name, vision_model_name, config=RTVTLMConfig(), **kwargs):
        """Load pretrained language and vision models"""
        # Load base language model config first

        base_lm_config = Qwen2Config.from_pretrained(language_model_name, **kwargs)
        
        # Merge with provided config to preserve adapter settings
        merged_config = merge_configs(config, base_lm_config)
        
        # Load vision config and merge
        vision_config = CLIPConfig.from_pretrained(vision_model_name, **kwargs).vision_config
        merged_config.vision_config = merge_configs(merged_config.vision_config, vision_config)

        model = cls(merged_config)

        language_model = Qwen2ForCausalLM.from_pretrained(language_model_name, **kwargs)
        model.model.load_state_dict(language_model.model.state_dict(), strict=False)
        model.lm_head.load_state_dict(language_model.lm_head.state_dict(), strict=False)
        del language_model
        model.vision_embedder = CLIPVisionModel.from_pretrained(vision_model_name, **kwargs)

        # Clean up to free memory
        torch.cuda.empty_cache() if torch.cuda.is_available() else None
        
        return model.to(device=kwargs.get("device_map", "cpu"), dtype=kwargs.get("dtype", torch.float32))

    def encode_vision(self, pixel_values):
        """Encode vision inputs and cache the features for generation"""
        with torch.no_grad():
            return self.vision_embedder(pixel_values).last_hidden_state

    def generate(self, input_ids=None, pixel_values = None, attention_mask=None, **kwargs):
        vision_features = self.encode_vision(pixel_values)
        
        # Call parent generate with embeddings
        return super().generate(
            vision_features=vision_features,
            input_ids=input_ids,
            attention_mask=attention_mask,
            **kwargs
        )


    @can_return_tuple
    @auto_docstring
    def forward(
        self,
        vision_features: Optional[torch.FloatTensor] = None,
        input_ids: Optional[torch.LongTensor] = None,
        attention_mask: Optional[torch.Tensor] = None,
        position_ids: Optional[torch.LongTensor] = None,
        past_key_values: Optional[Cache] = None,
        inputs_embeds: Optional[torch.FloatTensor] = None,
        labels: Optional[torch.LongTensor] = None,
        use_cache: Optional[bool] = None,
        cache_position: Optional[torch.LongTensor] = None,
        logits_to_keep: Union[int, torch.Tensor] = 0,
        **kwargs: Unpack[TransformersKwargs],
    ) -> CausalLMOutputWithPast:
        """
        Args:
            vision_features (`torch.FloatTensor` of shape `(batch_size, sequence_length, hidden_size)`, *optional*):
                Vision features from the vision encoder to be integrated via cross-attention adapters.
        """

        # Only pass vision_features if they exist
        outputs: BaseModelOutputWithPast = self.model(
            vision_features=vision_features,
            input_ids=input_ids,
            attention_mask=attention_mask,
            position_ids=position_ids,
            past_key_values=past_key_values,
            inputs_embeds=inputs_embeds,
            use_cache=use_cache,
            cache_position=cache_position,
            **kwargs,
        )

        hidden_states = outputs.last_hidden_state
        # Only compute necessary logits, and do not upcast them to float if we are not computing the loss
        slice_indices = slice(-logits_to_keep, None) if isinstance(logits_to_keep, int) else logits_to_keep
        logits = self.lm_head(hidden_states[:, slice_indices, :])

        loss = None
        if labels is not None:
            loss = self.loss_function(logits=logits, labels=labels, vocab_size=self.config.vocab_size, **kwargs)

        return CausalLMOutputWithPast(
            loss=loss,
            logits=logits,
            past_key_values=outputs.past_key_values,
            hidden_states=outputs.hidden_states,
            attentions=outputs.attentions,
        )